name: questao_04
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/emanuel.jpg
    - images/skibrand.jpg
    - images/design.png

  fonts:
    - family: Instagram
      fonts: 
       - asset: fonts\Instagram.ttf

    - family: GitHub
      fonts:
       - asset: fonts\GitHub.ttf